/* Generated by l0c, the Dea/L0 compiler. Do not edit. */

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

/* Include SipHash runtime implementation in main translation unit */
#define SIPHASH_IMPLEMENTATION
#include "l0_siphash.h"

/* L1 runtime header */
#include "l1_runtime.h"

/* Forward declarations */

/* Optional wrapper types (builtins / early) */
/* Type definitions (dependency-ordered) */
/* Optional wrapper types (late) */
/* Function declarations */
/* Module: main */
dea_int dea_main_main(void);
/* Module: dep1 */
dea_int dea_dep1_f(void);
/* Module: leaf */
dea_int dea_leaf_h(void);
/* Module: dep2 */
dea_int dea_dep2_g(void);
/* Function definitions */
/* -------------------------------- */
/* Module: main */
/* -------------------------------- */
dea_int dea_main_main(void)
{
    return (_rt_iadd(dea_dep1_f(), dea_dep2_g()));
}

/* -------------------------------- */
/* Module: dep1 */
/* -------------------------------- */
dea_int dea_dep1_f(void)
{
    return dea_leaf_h();
}

/* -------------------------------- */
/* Module: leaf */
/* -------------------------------- */
dea_int dea_leaf_h(void)
{
    return 3;
}

/* -------------------------------- */
/* Module: dep2 */
/* -------------------------------- */
dea_int dea_dep2_g(void)
{
    return 2;
}

/* C entry point wrapper */
int main(int argc, char **argv)
{
    _rt_init_args(argc, argv);
    return (int) dea_main_main();
}
