#!/bin/bash
#
# SPDX-License-Identifier: MIT OR Apache-2.0
# Copyright (c) 2026 gwz
#

DIR=$(dirname "$0")

# Set the L0_HOME environment variable to point to the compiler root if not already set.
export L0_HOME="${L0_HOME:-$DIR/compiler}"

python3 "$L0_HOME/stage1_py/l0c.py" "$@"
