/* Generated by l0c, the Dea/L0 compiler. Do not edit. */

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

/* Include SipHash runtime implementation in main translation unit */
#define SIPHASH_IMPLEMENTATION
#include "l0_siphash.h"

/* L0 runtime header */
#include "l0_runtime.h"

/* Forward declarations */

/* Optional wrapper types (builtins / early) */
/* Type definitions (dependency-ordered) */
/* Optional wrapper types (late) */
/* Function declarations */
/* Module: main */
l0_int l0_main_main(void);
/* Function definitions */
/* -------------------------------- */
/* Module: main */
/* -------------------------------- */
l0_int l0_main_main(void)
{
    return 0;
}

/* C entry point wrapper */
int main(int argc, char **argv)
{
    _rt_init_args(argc, argv);
    return (int) l0_main_main();
}
