/* Generated by l0c, the Dea/L0 compiler. Do not edit. */

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

/* Include SipHash runtime implementation in main translation unit */
#define SIPHASH_IMPLEMENTATION
#include "l0_siphash.h"

/* L1 runtime header */
#include "l1_runtime.h"

/* Forward declarations */
struct dea_main_MaybeInt;

/* Optional wrapper types (builtins / early) */
/* Type definitions (dependency-ordered) */
#ifndef DEA_DEFINED_dea_main_MaybeInt
#define DEA_DEFINED_dea_main_MaybeInt
enum dea_main_MaybeInt_tag {
    dea_main_MaybeInt_None,
    dea_main_MaybeInt_Some,
};

struct dea_main_MaybeInt {
    enum dea_main_MaybeInt_tag tag;
    union {
        struct { char __dummy__; } None;
        struct { dea_int value; } Some;
    } data;
};
#endif

/* Optional wrapper types (late) */
/* Function declarations */
/* Module: main */
struct dea_main_MaybeInt dea_main_make(dea_bool flag);
dea_int dea_main_main(void);
/* Function definitions */
/* -------------------------------- */
/* Module: main */
/* -------------------------------- */
struct dea_main_MaybeInt dea_main_make(dea_bool flag)
{
    dea_bool dea_cond_1 = 0;
    {
        {
            if (flag)
            {
                goto __cond_true_1;
            }
        }
        goto __cond_false_2;
    __cond_true_1:;
        dea_cond_1 = 1;
        goto __cond_end_3;
    __cond_false_2:;
    __cond_end_3:;
    }
    if (dea_cond_1)
    {
        return (struct dea_main_MaybeInt){ .tag = dea_main_MaybeInt_Some, .data = { .Some = { .value = 7 } } };
    }
    return (struct dea_main_MaybeInt){ .tag = dea_main_MaybeInt_None };
}

dea_int dea_main_main(void)
{
    dea_int total = 0;
    {
        dea_int _scrutinee = 1;
        switch (_scrutinee) {
        case 0:
        {
            {
                total = 1;
            }
            break;
        }
        default:
        {
            {
                total = 2;
            }
            break;
        }
        }
    }
    {
        struct dea_main_MaybeInt _scrutinee = dea_main_make(1);
        switch ((_scrutinee).tag) {
        case dea_main_MaybeInt_Some:
        {
            dea_int v = (_scrutinee).data.Some.value;
            total = (_rt_iadd(total, v));
            break;
        }
        case dea_main_MaybeInt_None:
        {
            total = 0;
            break;
        }
        }
    }
    return total;
}

/* C entry point wrapper */
int main(int argc, char **argv)
{
    _rt_init_args(argc, argv);
    return (int) dea_main_main();
}
