/* Generated by l0c, the Dea/L0 compiler. Do not edit. */

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

/* Include SipHash runtime implementation in main translation unit */
#define SIPHASH_IMPLEMENTATION
#include "l0_siphash.h"

/* L0 runtime header */
#include "l0_runtime.h"

/* Forward declarations */
struct l0_main_MaybeInt;

/* Optional wrapper types (builtins / early) */
/* Type definitions (dependency-ordered) */
#ifndef L0_DEFINED_l0_main_MaybeInt
#define L0_DEFINED_l0_main_MaybeInt
enum l0_main_MaybeInt_tag {
    l0_main_MaybeInt_None,
    l0_main_MaybeInt_Some,
};

struct l0_main_MaybeInt {
    enum l0_main_MaybeInt_tag tag;
    union {
        struct { char __dummy__; } None;
        struct { l0_int value; } Some;
    } data;
};
#endif

/* Optional wrapper types (late) */
/* Function declarations */
/* Module: main */
struct l0_main_MaybeInt l0_main_make(l0_bool flag);
l0_int l0_main_main(void);
/* Function definitions */
/* -------------------------------- */
/* Module: main */
/* -------------------------------- */
struct l0_main_MaybeInt l0_main_make(l0_bool flag)
{
    l0_bool l0_cond_1 = 0;
    {
        {
            if (flag)
            {
                goto __cond_true_1;
            }
        }
        goto __cond_false_2;
    __cond_true_1:;
        l0_cond_1 = 1;
        goto __cond_end_3;
    __cond_false_2:;
    __cond_end_3:;
    }
    if (l0_cond_1)
    {
        return (struct l0_main_MaybeInt){ .tag = l0_main_MaybeInt_Some, .data = { .Some = { .value = 7 } } };
    }
    return (struct l0_main_MaybeInt){ .tag = l0_main_MaybeInt_None };
}

l0_int l0_main_main(void)
{
    l0_int total = 0;
    {
        l0_int _scrutinee = 1;
        switch (_scrutinee) {
        case 0:
        {
            {
                total = 1;
            }
            break;
        }
        default:
        {
            {
                total = 2;
            }
            break;
        }
        }
    }
    {
        struct l0_main_MaybeInt _scrutinee = l0_main_make(1);
        switch (_scrutinee.tag) {
        case l0_main_MaybeInt_Some:
        {
            l0_int v = _scrutinee.data.Some.value;
            total = (_rt_iadd(total, v));
            break;
        }
        case l0_main_MaybeInt_None:
        {
            total = 0;
            break;
        }
        }
    }
    return total;
}

/* C entry point wrapper */
int main(int argc, char **argv)
{
    _rt_init_args(argc, argv);
    return (int) l0_main_main();
}
