/* Generated by l0c, the Dea/L0 compiler. Do not edit. */

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

/* Include SipHash runtime implementation in main translation unit */
#define SIPHASH_IMPLEMENTATION
#include "l0_siphash.h"

/* L1 runtime header */
#include "l1_runtime.h"

/* Forward declarations */

/* Optional wrapper types (builtins / early) */
#ifndef L0_OPT_INT_DEFINED
#define L0_OPT_INT_DEFINED
typedef struct { l0_bool has_value; l0_int value; } l0_opt_int;
#endif /* L0_OPT_INT_DEFINED */

/* Type definitions (dependency-ordered) */
/* Optional wrapper types (late) */
/* Function declarations */
/* Module: main */
l0_opt_int l0_main_value_none(void);
l0_int* l0_main_ptr_none(void);
l0_bool l0_main_is_none_value(l0_opt_int x);
l0_bool l0_main_is_none_ptr(l0_int* x);
l0_int l0_main_helper(void);
l0_int l0_main_main(void);
/* Function definitions */
/* -------------------------------- */
/* Module: main */
/* -------------------------------- */
l0_opt_int l0_main_value_none(void)
{
    return ((l0_opt_int){.has_value = 0});
}

l0_int* l0_main_ptr_none(void)
{
    return NULL;
}

l0_bool l0_main_is_none_value(l0_opt_int x)
{
    return (!((x).has_value));
}

l0_bool l0_main_is_none_ptr(l0_int* x)
{
    return (x == NULL);
}

l0_int l0_main_helper(void)
{
    {
        /* null literal */
        {
            /* null literal */
            l0_int l0_ret_1 = 1;
            {
                return 2;
            }
            return l0_ret_1;
        }
    }
}

l0_int l0_main_main(void)
{
    l0_opt_int x = ((l0_opt_int){.has_value = 0});
    l0_int* p = NULL;
    l0_bool l0_cond_2 = 0;
    {
        {
            if (l0_main_is_none_value(x))
            {
                goto __cond_rhs_7;
            }
        }
        goto __cond_false_2;
    __cond_rhs_7:;
        {
            if (l0_main_is_none_ptr(p))
            {
                goto __cond_rhs_6;
            }
        }
        goto __cond_false_2;
    __cond_rhs_6:;
        {
            if ((!((l0_main_value_none()).has_value)))
            {
                goto __cond_rhs_5;
            }
        }
        goto __cond_false_2;
    __cond_rhs_5:;
        {
            if ((l0_main_ptr_none() == NULL))
            {
                goto __cond_rhs_4;
            }
        }
        goto __cond_false_2;
    __cond_rhs_4:;
        {
            if ((l0_main_helper() == 2))
            {
                goto __cond_true_1;
            }
        }
        goto __cond_false_2;
    __cond_true_1:;
        l0_cond_2 = 1;
        goto __cond_end_3;
    __cond_false_2:;
    __cond_end_3:;
    }
    if (l0_cond_2)
    {
        return 0;
    }
    return 1;
}

/* C entry point wrapper */
int main(int argc, char **argv)
{
    _rt_init_args(argc, argv);
    return (int) l0_main_main();
}
