/* Generated by l0c, the Dea/L0 compiler. Do not edit. */

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

/* Include SipHash runtime implementation in main translation unit */
#define SIPHASH_IMPLEMENTATION
#include "l0_siphash.h"

/* L1 runtime header */
#include "l1_runtime.h"

/* Forward declarations */

/* Optional wrapper types (builtins / early) */
#ifndef DEA_OPT_INT_DEFINED
#define DEA_OPT_INT_DEFINED
typedef struct { dea_bool has_value; dea_int value; } dea_opt_int;
#endif /* DEA_OPT_INT_DEFINED */

/* Type definitions (dependency-ordered) */
/* Optional wrapper types (late) */
/* Function declarations */
/* Module: main */
dea_opt_int dea_main_value_none(void);
dea_int* dea_main_ptr_none(void);
dea_bool dea_main_is_none_value(dea_opt_int x);
dea_bool dea_main_is_none_ptr(dea_int* x);
dea_int dea_main_helper(void);
dea_int dea_main_main(void);
/* Function definitions */
/* -------------------------------- */
/* Module: main */
/* -------------------------------- */
dea_opt_int dea_main_value_none(void)
{
    return ((dea_opt_int){.has_value = 0});
}

dea_int* dea_main_ptr_none(void)
{
    return NULL;
}

dea_bool dea_main_is_none_value(dea_opt_int x)
{
    return (!((x).has_value));
}

dea_bool dea_main_is_none_ptr(dea_int* x)
{
    return (x == NULL);
}

dea_int dea_main_helper(void)
{
    {
        /* null literal */
        {
            /* null literal */
            dea_int dea_ret_1 = 1;
            {
                return 2;
            }
            return dea_ret_1;
        }
    }
}

dea_int dea_main_main(void)
{
    dea_opt_int x = ((dea_opt_int){.has_value = 0});
    dea_int* p = NULL;
    dea_bool dea_cond_2 = 0;
    {
        {
            if (dea_main_is_none_value(x))
            {
                goto __cond_rhs_7;
            }
        }
        goto __cond_false_2;
    __cond_rhs_7:;
        {
            if (dea_main_is_none_ptr(p))
            {
                goto __cond_rhs_6;
            }
        }
        goto __cond_false_2;
    __cond_rhs_6:;
        {
            if ((!((dea_main_value_none()).has_value)))
            {
                goto __cond_rhs_5;
            }
        }
        goto __cond_false_2;
    __cond_rhs_5:;
        {
            if ((dea_main_ptr_none() == NULL))
            {
                goto __cond_rhs_4;
            }
        }
        goto __cond_false_2;
    __cond_rhs_4:;
        {
            if ((dea_main_helper() == 2))
            {
                goto __cond_true_1;
            }
        }
        goto __cond_false_2;
    __cond_true_1:;
        dea_cond_2 = 1;
        goto __cond_end_3;
    __cond_false_2:;
    __cond_end_3:;
    }
    if (dea_cond_2)
    {
        return 0;
    }
    return 1;
}

/* C entry point wrapper */
int main(int argc, char **argv)
{
    _rt_init_args(argc, argv);
    return (int) dea_main_main();
}
