/* Generated by l0c, the Dea/L0 compiler. Do not edit. */

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

/* Include SipHash runtime implementation in main translation unit */
#define SIPHASH_IMPLEMENTATION
#include "l0_siphash.h"

/* L0 runtime header */
#include "l0_runtime.h"

/* Forward declarations */

/* Optional wrapper types (builtins / early) */
/* Type definitions (dependency-ordered) */
/* Optional wrapper types (late) */
/* Function declarations */
/* Module: main */
l0_int l0_main_main(void);
/* Function definitions */
/* -------------------------------- */
/* Module: main */
/* -------------------------------- */
l0_int l0_main_main(void)
{
    l0_string s = ((l0_string)L0_STRING_CONST("hi", 2));
    l0_string l0_copy_1 = s;
    rt_string_retain(l0_copy_1);
    l0_string t = l0_copy_1;
    {
        l0_string l0_copy_2 = t;
        rt_string_retain(l0_copy_2);
        l0_string x = l0_copy_2;
        {
            l0_string l0_copy_3 = x;
            rt_string_retain(l0_copy_3);
            l0_string y = l0_copy_3;
            rt_string_release(y);
        }
        {
            l0_string l0_copy_4 = x;
            rt_string_retain(l0_copy_4);
            l0_string z = l0_copy_4;
            rt_string_release(z);
        }
        rt_string_release(x);
    }
    l0_int l0_ret_5 = 0;
    rt_string_release(t);
    rt_string_release(s);
    return l0_ret_5;
}

/* C entry point wrapper */
int main(int argc, char **argv)
{
    _rt_init_args(argc, argv);
    return (int) l0_main_main();
}
