/* Generated by l0c, the Dea/L0 compiler. Do not edit. */

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

/* Include SipHash runtime implementation in main translation unit */
#define SIPHASH_IMPLEMENTATION
#include "l0_siphash.h"

/* L1 runtime header */
#include "l1_runtime.h"

/* Forward declarations */
struct dea_main_Flag;
struct dea_main_Pair;

/* Optional wrapper types (builtins / early) */
/* Type definitions (dependency-ordered) */
#ifndef DEA_DEFINED_dea_main_Pair
#define DEA_DEFINED_dea_main_Pair
struct dea_main_Pair {
    dea_int left;
    dea_int right;
};
#endif

#ifndef DEA_DEFINED_dea_main_Flag
#define DEA_DEFINED_dea_main_Flag
enum dea_main_Flag_tag {
    dea_main_Flag_Off,
    dea_main_Flag_On,
};

struct dea_main_Flag {
    enum dea_main_Flag_tag tag;
    union {
        struct { char __dummy__; } Off;
        struct { char __dummy__; } On;
    } data;
};
#endif

/* Optional wrapper types (late) */
/* Function declarations */
/* Module: main */
dea_int dea_main_main(void);
/* Function definitions */
/* -------------------------------- */
/* Module: main */
/* -------------------------------- */
dea_int dea_main_main(void)
{
    struct dea_main_Pair p = (struct dea_main_Pair){ .left = 1, .right = ((dea_int)sizeof(struct dea_main_Pair)) };
    struct dea_main_Flag f = (struct dea_main_Flag){ .tag = dea_main_Flag_On };
    return (_rt_iadd((p).right, ((dea_int)((f).tag))));
}

/* C entry point wrapper */
int main(int argc, char **argv)
{
    _rt_init_args(argc, argv);
    return (int) dea_main_main();
}
