/* Generated by l0c, the Dea/L0 compiler. Do not edit. */

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

/* Include SipHash runtime implementation in main translation unit */
#define SIPHASH_IMPLEMENTATION
#include "l0_siphash.h"

/* L1 runtime header */
#include "l1_runtime.h"

/* Forward declarations */
struct dea_main_Point;
struct dea_main_MaybePoint;

/* Optional wrapper types (builtins / early) */
/* Type definitions (dependency-ordered) */
#ifndef DEA_DEFINED_dea_main_Point
#define DEA_DEFINED_dea_main_Point
struct dea_main_Point {
    dea_int x;
    dea_int y;
};
#endif

#ifndef DEA_DEFINED_dea_main_MaybePoint
#define DEA_DEFINED_dea_main_MaybePoint
enum dea_main_MaybePoint_tag {
    dea_main_MaybePoint_None,
    dea_main_MaybePoint_Some,
};

struct dea_main_MaybePoint {
    enum dea_main_MaybePoint_tag tag;
    union {
        struct { char __dummy__; } None;
        struct { struct dea_main_Point value; } Some;
    } data;
};
#endif

/* Optional wrapper types (late) */
/* Top-level let declarations */
/* Module: main */
static struct dea_main_Point dea_main_origin = { .x = 0, .y = 0 };
/* Function declarations */
/* Module: main */
dea_int dea_main_main(void);
/* Function definitions */
/* -------------------------------- */
/* Module: main */
/* -------------------------------- */
dea_int dea_main_main(void)
{
    struct dea_main_Point p = dea_main_origin;
    return (p).x;
}

/* C entry point wrapper */
int main(int argc, char **argv)
{
    _rt_init_args(argc, argv);
    return (int) dea_main_main();
}
