/* Generated by l0c, the Dea/L0 compiler. Do not edit. */

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

/* Include SipHash runtime implementation in main translation unit */
#define SIPHASH_IMPLEMENTATION
#include "l0_siphash.h"

/* L1 runtime header */
#include "l1_runtime.h"

/* Forward declarations */
struct l0_main_Point;
struct l0_main_MaybePoint;

/* Optional wrapper types (builtins / early) */
/* Type definitions (dependency-ordered) */
#ifndef L0_DEFINED_l0_main_Point
#define L0_DEFINED_l0_main_Point
struct l0_main_Point {
    l0_int x;
    l0_int y;
};
#endif

#ifndef L0_DEFINED_l0_main_MaybePoint
#define L0_DEFINED_l0_main_MaybePoint
enum l0_main_MaybePoint_tag {
    l0_main_MaybePoint_None,
    l0_main_MaybePoint_Some,
};

struct l0_main_MaybePoint {
    enum l0_main_MaybePoint_tag tag;
    union {
        struct { char __dummy__; } None;
        struct { struct l0_main_Point value; } Some;
    } data;
};
#endif

/* Optional wrapper types (late) */
/* Top-level let declarations */
/* Module: main */
static struct l0_main_Point l0_main_origin = { .x = 0, .y = 0 };
/* Function declarations */
/* Module: main */
l0_int l0_main_main(void);
/* Function definitions */
/* -------------------------------- */
/* Module: main */
/* -------------------------------- */
l0_int l0_main_main(void)
{
    struct l0_main_Point p = l0_main_origin;
    return (p).x;
}

/* C entry point wrapper */
int main(int argc, char **argv)
{
    _rt_init_args(argc, argv);
    return (int) l0_main_main();
}
