/* Generated by l0c, the Dea/L0 compiler. Do not edit. */

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

/* Include SipHash runtime implementation in main translation unit */
#define SIPHASH_IMPLEMENTATION
#include "l0_siphash.h"

/* L1 runtime header */
#include "l1_runtime.h"

/* Forward declarations */

/* Optional wrapper types (builtins / early) */
/* Type definitions (dependency-ordered) */
/* Optional wrapper types (late) */
/* Function declarations */
/* Module: main */
dea_int dea_main_main(void);
/* Function definitions */
/* -------------------------------- */
/* Module: main */
/* -------------------------------- */
dea_int dea_main_main(void)
{
    dea_string s = ((dea_string)DEA_STRING_CONST("hi", 2));
    dea_string dea_copy_1 = s;
    rt_string_retain(dea_copy_1);
    dea_string t = dea_copy_1;
    {
        dea_string dea_copy_2 = t;
        rt_string_retain(dea_copy_2);
        dea_string x = dea_copy_2;
        {
            dea_string dea_copy_3 = x;
            rt_string_retain(dea_copy_3);
            dea_string y = dea_copy_3;
            rt_string_release(y);
        }
        {
            dea_string dea_copy_4 = x;
            rt_string_retain(dea_copy_4);
            dea_string z = dea_copy_4;
            rt_string_release(z);
        }
        rt_string_release(x);
    }
    dea_int dea_ret_5 = 0;
    rt_string_release(t);
    rt_string_release(s);
    return dea_ret_5;
}

/* C entry point wrapper */
int main(int argc, char **argv)
{
    _rt_init_args(argc, argv);
    return (int) dea_main_main();
}
