/* Generated by L0 compiler */

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

/* Include SipHash runtime implementation in main translation unit */
#define SIPHASH_IMPLEMENTATION
#include "l0_siphash.h"

/* L0 runtime header */
#include "l0_runtime.h"

/* Forward declarations */

/* Optional wrapper types (builtins / early) */
/* Type definitions (dependency-ordered) */
/* Optional wrapper types (late) */
/* Function declarations */
/* Module: main */
l0_int l0_main_add(l0_int a, l0_int b);
l0_int l0_main_main(void);
/* Function definitions */
/* -------------------------------- */
/* Module: main */
/* -------------------------------- */
l0_int l0_main_add(l0_int a, l0_int b)
{
    return (_rt_iadd(a, b));
}

l0_int l0_main_main(void)
{
    l0_int sum = 0;
    // for loop
    {
        l0_int i = 0;
        while ((i < 3))
        {
            {
                if ((i < 2))
                {
                    sum = (_rt_iadd(sum, l0_main_add(i, 1)));
                }
            }
        __lcont_2:;
            i = (_rt_iadd(i, 1));
        }
    }
__lbrk_1:;
    while ((sum > 0))
    {
        return sum;
    __lcont_4:;
    }
__lbrk_3:;
    return 0;
}

/* C entry point wrapper */
int main(int argc, char **argv)
{
    _rt_init_args(argc, argv);
    return (int) l0_main_main();
}
