/* Generated by l0c, the Dea/L0 compiler. Do not edit. */

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

/* Include SipHash runtime implementation in main translation unit */
#define SIPHASH_IMPLEMENTATION
#include "l0_siphash.h"

/* L0 runtime header */
#include "l0_runtime.h"

/* Forward declarations */

/* Optional wrapper types (builtins / early) */
/* Type definitions (dependency-ordered) */
/* Optional wrapper types (late) */
/* Function declarations */
/* Module: main */
l0_int l0_main_add(l0_int a, l0_int b);
l0_int l0_main_main(void);
/* Function definitions */
/* -------------------------------- */
/* Module: main */
/* -------------------------------- */
l0_int l0_main_add(l0_int a, l0_int b)
{
    return (_rt_iadd(a, b));
}

l0_int l0_main_main(void)
{
    l0_int sum = 0;
    // for loop
    {
        l0_int i = 0;
        while (1)
        {
            l0_bool l0_cond_1 = 0;
            {
                {
                    if ((i < 3))
                    {
                        goto __cond_true_3;
                    }
                }
                goto __cond_false_4;
            __cond_true_3:;
                l0_cond_1 = 1;
                goto __cond_end_5;
            __cond_false_4:;
            __cond_end_5:;
            }
            if (!(l0_cond_1))
            {
                goto __lbrk_1;
            }
            {
                l0_bool l0_cond_2 = 0;
                {
                    {
                        if ((i < 2))
                        {
                            goto __cond_true_6;
                        }
                    }
                    goto __cond_false_7;
                __cond_true_6:;
                    l0_cond_2 = 1;
                    goto __cond_end_8;
                __cond_false_7:;
                __cond_end_8:;
                }
                if (l0_cond_2)
                {
                    sum = (_rt_iadd(sum, l0_main_add(i, 1)));
                }
            }
        __lcont_2:;
            i = (_rt_iadd(i, 1));
        }
    }
__lbrk_1:;
    while (1)
    {
        l0_bool l0_cond_3 = 0;
        {
            {
                if ((sum > 0))
                {
                    goto __cond_true_11;
                }
            }
            goto __cond_false_12;
        __cond_true_11:;
            l0_cond_3 = 1;
            goto __cond_end_13;
        __cond_false_12:;
        __cond_end_13:;
        }
        if (!(l0_cond_3))
        {
            goto __lbrk_9;
        }
        return sum;
    __lcont_10:;
    }
__lbrk_9:;
    return 0;
}

/* C entry point wrapper */
int main(int argc, char **argv)
{
    _rt_init_args(argc, argv);
    return (int) l0_main_main();
}
