/* Generated by l0c, the Dea/L0 compiler. Do not edit. */

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

/* Include SipHash runtime implementation in main translation unit */
#define SIPHASH_IMPLEMENTATION
#include "dea_siphash.h"

/* L0 runtime header */
#include "l0_runtime.h"

/* Forward declarations */
struct l0_main_Flag;
struct l0_main_Pair;

/* Optional wrapper types (builtins / early) */
/* Type definitions (dependency-ordered) */
#ifndef L0_DEFINED_l0_main_Pair
#define L0_DEFINED_l0_main_Pair
struct l0_main_Pair {
    l0_int left;
    l0_int right;
};
#endif

#ifndef L0_DEFINED_l0_main_Flag
#define L0_DEFINED_l0_main_Flag
enum l0_main_Flag_tag {
    l0_main_Flag_Off,
    l0_main_Flag_On,
};

struct l0_main_Flag {
    enum l0_main_Flag_tag tag;
    union {
        struct { char __dummy__; } Off;
        struct { char __dummy__; } On;
    } data;
};
#endif

/* Optional wrapper types (late) */
/* Function declarations */
/* Module: main */
l0_int l0_main_main(void);
/* Function definitions */
/* -------------------------------- */
/* Module: main */
/* -------------------------------- */
l0_int l0_main_main(void)
{
    struct l0_main_Pair p = (struct l0_main_Pair){ .left = 1, .right = ((l0_int)sizeof(struct l0_main_Pair)) };
    struct l0_main_Flag f = (struct l0_main_Flag){ .tag = l0_main_Flag_On };
    return (_rt_iadd((p).right, ((l0_int)((f).tag))));
}

/* C entry point wrapper */
int main(int argc, char **argv)
{
    _rt_init_args(argc, argv);
    int l0_exit_code = (int) l0_main_main();
    return l0_exit_code;
}
